//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::contest::Entity as Contest;
pub use super::privilege::Entity as Privilege;
pub use super::problem::Entity as Problem;
pub use super::record::Entity as Record;
pub use super::user::Entity as User;
